build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related qa APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (666) 555-1234
    - (666) 523-1345