build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank cards related prod APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (777) 555-1234
    - (777) 523-1345